# Generated by Django 3.2.15 on 2023-09-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='image',
            field=models.ImageField(default=0, upload_to='recipes/media/', verbose_name='Изображение рецепта'),
            preserve_default=False,
        ),
    ]
